# Configuration for energy system simulation
# Date: Thu 14rd of August 2019
# Author: Jakob Wolf (jakob.wolf@beuth-hochschule.de)

run_model: True
display_results: True

# Set True to run your own analysis script on the results.
# Requires a function 'my_detailed_analysis' within a
# module 'detailed_analysis.py'
run_detailed_analysis: False

debug: False
solver: 'cbc'
solver_verbose: False

number_of_teams: 1
team_names:
#  - '1'   # 01
  - 'Forchdorf' # 01

# Specific energy system design of each team
design_parameters_file_name:
  - 'parameters_Team_01.csv'
  
# Parameters and technical specifications
# (same for energy systems of all teams)
parameters_file_name:  'general_parameters.csv'

# Input time series
# (electrical demand, district heating demand,
#  irradiation, wind power output)
time_series_file_name: 'DAT_Energie-Workshop.CSV'
##time_series_file_name: 'time_series_hourly_values.CSV'
